name: Build and push
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: kaniko
    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        run: >-
          /data/docker-build --build-arg=COMMIT_SHA=${{ github.sha }} --build-arg=COMMIT_DATE=${{
          github.event.head_commit.timestamp }} "--build-arg=COMMIT_SUBJECT=${{
          github.event.head_commit.message }}"
